#!/bin/bash
if [[ $(brew outdated node) ]]; then
    brew upgrade
fi
if [[ $(npm outdated) ]]; then
    npm i -g npm
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n stable
fi
npm cache verify
npm update -g
exit 0
